// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sigevet.Models;

#nullable disable

namespace sigevet.Migrations
{
    [DbContext(typeof(SigevetDbContext))]
    [Migration("20260424070021_Vacuna_Laboratorio")]
    partial class Vacuna_Laboratorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sigevet.Models.CategoriaEstado", b =>
                {
                    b.Property<int>("idCategoriaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategoriaEstado"));

                    b.Property<string>("categoriaEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("idCategoriaEstado");

                    b.ToTable("CategoriasEstado");
                });

            modelBuilder.Entity("sigevet.Models.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContacto"));

                    b.Property<string>("detalleContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoContacto")
                        .HasColumnType("int");

                    b.Property<int>("idLabotarioContacto")
                        .HasColumnType("int");

                    b.Property<int>("idPersonaContacto")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContacto")
                        .HasColumnType("int");

                    b.HasKey("idContacto");

                    b.HasIndex("idEstadoContacto");

                    b.HasIndex("idLabotarioContacto");

                    b.HasIndex("idPersonaContacto");

                    b.HasIndex("idTipoContacto");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("sigevet.Models.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("sigevet.Models.EspecialidadVeterinario", b =>
                {
                    b.Property<int>("idVeterinarioEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVeterinarioEspecialidad"));

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("idVeterinario")
                        .HasColumnType("int");

                    b.HasKey("idVeterinarioEspecialidad");

                    b.HasIndex("idEspecialidad");

                    b.HasIndex("idVeterinario");

                    b.ToTable("EspecialidadesVeterinario");
                });

            modelBuilder.Entity("sigevet.Models.Especie", b =>
                {
                    b.Property<int>("idEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecie"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("idEspecie");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstado"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCategoriaEstado")
                        .HasColumnType("int");

                    b.HasKey("idEstado");

                    b.HasIndex("idCategoriaEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("sigevet.Models.Laboratorio", b =>
                {
                    b.Property<int>("idLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLaboratorio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("laboratorio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("idLaboratorio");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.Property<int>("idMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMascota"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoMascota")
                        .HasColumnType("int");

                    b.Property<int>("idRaza")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("peso")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("seniasParticulares")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("idMascota");

                    b.HasIndex("idEstadoMascota");

                    b.HasIndex("idRaza");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.Property<int>("idPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersona"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoPersona")
                        .HasColumnType("int");

                    b.Property<int>("idTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("numeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPersona");

                    b.HasIndex("idEstadoPersona");

                    b.HasIndex("idTipoIdentificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("sigevet.Models.Raza", b =>
                {
                    b.Property<int>("idRaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRaza"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEspecie")
                        .HasColumnType("int");

                    b.Property<string>("raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRaza");

                    b.HasIndex("idEspecie");

                    b.ToTable("Razas");
                });

            modelBuilder.Entity("sigevet.Models.TipoContacto", b =>
                {
                    b.Property<int>("idTipoContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoContacto"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("tipoContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoContacto");

                    b.ToTable("TiposContacto");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("idTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoIdentificacion"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("tipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoIdentificacion");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.TipoVacuna", b =>
                {
                    b.Property<int>("idTipoVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoVacuna"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("tipoVacuna")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoVacuna");

                    b.ToTable("TiposVacuna");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.Property<int>("idPersonaTut")
                        .HasColumnType("int");

                    b.Property<bool>("autorizaNotificaciones")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaActualizacionTutor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRegistroTutor")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoCuentaTutor")
                        .HasColumnType("int");

                    b.HasKey("idPersonaTut");

                    b.HasIndex("idEstadoCuentaTutor");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("sigevet.Models.TutorMascota", b =>
                {
                    b.Property<int>("idTutorMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTutorMascota"));

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int>("idPersonaTut")
                        .HasColumnType("int");

                    b.HasKey("idTutorMascota");

                    b.HasIndex("idMascota");

                    b.HasIndex("idPersonaTut");

                    b.ToTable("TutoresMascota");
                });

            modelBuilder.Entity("sigevet.Models.Vacuna", b =>
                {
                    b.Property<int>("idVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVacuna"));

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaFabricacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoVacuna")
                        .HasColumnType("int");

                    b.Property<int>("idLaboratorio")
                        .HasColumnType("int");

                    b.Property<int>("idTipoVacuna")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("numeroLote")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("idVacuna");

                    b.HasIndex("idEstadoVacuna");

                    b.HasIndex("idLaboratorio");

                    b.HasIndex("idTipoVacuna");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.Property<int>("idPersonaVet")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualizacionVeterinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRegistroVeterinario")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoDisponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("numeroTarjetaProfesional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idPersonaVet");

                    b.HasIndex("idEstadoDisponibilidad");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("sigevet.Models.Contacto", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoContacto")
                        .WithMany()
                        .HasForeignKey("idEstadoContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Laboratorio", "laboratorio")
                        .WithMany()
                        .HasForeignKey("idLabotarioContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithMany("contactosPersona")
                        .HasForeignKey("idPersonaContacto")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoContacto", "tipoContacto")
                        .WithMany()
                        .HasForeignKey("idTipoContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoContacto");

                    b.Navigation("laboratorio");

                    b.Navigation("persona");

                    b.Navigation("tipoContacto");
                });

            modelBuilder.Entity("sigevet.Models.EspecialidadVeterinario", b =>
                {
                    b.HasOne("sigevet.Models.Especialidad", "especialidad")
                        .WithMany("veterinariosPorEspecialidad")
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Veterinario", "veterinarios")
                        .WithMany("especialidadesPorVeterinario")
                        .HasForeignKey("idVeterinario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");

                    b.Navigation("veterinarios");
                });

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.HasOne("sigevet.Models.CategoriaEstado", "categoriaEstado")
                        .WithMany("estadosPorCategoria")
                        .HasForeignKey("idCategoriaEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoriaEstado");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoMascota")
                        .WithMany()
                        .HasForeignKey("idEstadoMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Raza", "raza")
                        .WithMany()
                        .HasForeignKey("idRaza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("estadoMascota");

                    b.Navigation("raza");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoPersona")
                        .WithMany()
                        .HasForeignKey("idEstadoPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoIdentificacion", "tipoIdentificacion")
                        .WithMany("personas")
                        .HasForeignKey("idTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoPersona");

                    b.Navigation("tipoIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.Raza", b =>
                {
                    b.HasOne("sigevet.Models.Especie", "especie")
                        .WithMany("razasPorEspecie")
                        .HasForeignKey("idEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especie");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoCuenta")
                        .WithMany()
                        .HasForeignKey("idEstadoCuentaTutor")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithOne()
                        .HasForeignKey("sigevet.Models.Tutor", "idPersonaTut")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoCuenta");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("sigevet.Models.TutorMascota", b =>
                {
                    b.HasOne("sigevet.Models.Mascota", "mascota")
                        .WithMany("tutoresMascota")
                        .HasForeignKey("idMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Tutor", "tutor")
                        .WithMany("mascotasPorTutor")
                        .HasForeignKey("idPersonaTut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("mascota");

                    b.Navigation("tutor");
                });

            modelBuilder.Entity("sigevet.Models.Vacuna", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoVacuna")
                        .WithMany()
                        .HasForeignKey("idEstadoVacuna")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Laboratorio", "laboratorio")
                        .WithMany()
                        .HasForeignKey("idLaboratorio")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoVacuna", "tipoVacuna")
                        .WithMany()
                        .HasForeignKey("idTipoVacuna")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoVacuna");

                    b.Navigation("laboratorio");

                    b.Navigation("tipoVacuna");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoVeterinario")
                        .WithMany()
                        .HasForeignKey("idEstadoDisponibilidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithOne()
                        .HasForeignKey("sigevet.Models.Veterinario", "idPersonaVet")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoVeterinario");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("sigevet.Models.CategoriaEstado", b =>
                {
                    b.Navigation("estadosPorCategoria");
                });

            modelBuilder.Entity("sigevet.Models.Especialidad", b =>
                {
                    b.Navigation("veterinariosPorEspecialidad");
                });

            modelBuilder.Entity("sigevet.Models.Especie", b =>
                {
                    b.Navigation("razasPorEspecie");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.Navigation("tutoresMascota");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.Navigation("contactosPersona");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Navigation("personas");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.Navigation("mascotasPorTutor");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.Navigation("especialidadesPorVeterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
