// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sigevet.Models;

#nullable disable

namespace sigevet.Migrations
{
    [DbContext(typeof(SigevetDbContext))]
    [Migration("20260414000146_migracionEstadosPorPersona")]
    partial class migracionEstadosPorPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstado"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("sigevet.Models.Personas", b =>
                {
                    b.Property<int>("idPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersona"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoPersona")
                        .HasColumnType("int");

                    b.Property<int>("idTipoIidentificacion")
                        .HasColumnType("int");

                    b.Property<string>("numeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPersona");

                    b.HasIndex("idEstadoPersona");

                    b.HasIndex("idTipoIidentificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("idTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoIdentificacion"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("tipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoIdentificacion");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.Personas", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoPersona")
                        .WithMany("estadosPersonas")
                        .HasForeignKey("idEstadoPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoIdentificacion", "tipoIdentificacion")
                        .WithMany("personas")
                        .HasForeignKey("idTipoIidentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoPersona");

                    b.Navigation("tipoIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.Navigation("estadosPersonas");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Navigation("personas");
                });
#pragma warning restore 612, 618
        }
    }
}
