// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sigevet.Models;

#nullable disable

namespace sigevet.Migrations
{
    [DbContext(typeof(SigevetDbContext))]
    [Migration("20260511002644_UpdatePasswordFieldName")]
    partial class UpdatePasswordFieldName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sigevet.Models.AlertaVacunacion", b =>
                {
                    b.Property<int>("idAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAlerta"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("fechaGeneracion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaProgramada")
                        .HasColumnType("date");

                    b.Property<int>("idTipoAlerta")
                        .HasColumnType("int");

                    b.Property<int>("idVacunacion")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idAlerta");

                    b.HasIndex("idTipoAlerta");

                    b.HasIndex("idVacunacion");

                    b.ToTable("AlertasVacunacion");
                });

            modelBuilder.Entity("sigevet.Models.Brigada", b =>
                {
                    b.Property<int>("idBrigada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBrigada"));

                    b.Property<string>("cobertura")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("fechaBrigada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("horaFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("horaInicio")
                        .HasColumnType("time");

                    b.Property<int>("idEstadoBrigada")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("nombreBrigada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idBrigada");

                    b.HasIndex("idEstadoBrigada");

                    b.ToTable("Brigadas");
                });

            modelBuilder.Entity("sigevet.Models.BrigadaVeterinario", b =>
                {
                    b.Property<int>("idBrigadaVeterinario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBrigadaVeterinario"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idBrigada")
                        .HasColumnType("int");

                    b.Property<int>("idRolParticipacion")
                        .HasColumnType("int");

                    b.Property<int>("idVeterinario")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idBrigadaVeterinario");

                    b.HasIndex("idBrigada");

                    b.HasIndex("idRolParticipacion");

                    b.HasIndex("idVeterinario", "idBrigada", "idRolParticipacion")
                        .IsUnique();

                    b.ToTable("BrigadasVeterinario");
                });

            modelBuilder.Entity("sigevet.Models.CategoriaEstado", b =>
                {
                    b.Property<int>("idCategoriaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategoriaEstado"));

                    b.Property<string>("categoriaEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idCategoriaEstado");

                    b.ToTable("CategoriasEstado");
                });

            modelBuilder.Entity("sigevet.Models.Contacto", b =>
                {
                    b.Property<int>("idContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContacto"));

                    b.Property<string>("detalleContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoContacto")
                        .HasColumnType("int");

                    b.Property<int?>("idLaboratorioContacto")
                        .HasColumnType("int");

                    b.Property<int?>("idPersonaContacto")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContacto")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idContacto");

                    b.HasIndex("idEstadoContacto");

                    b.HasIndex("idLaboratorioContacto");

                    b.HasIndex("idPersonaContacto");

                    b.HasIndex("idTipoContacto");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("sigevet.Models.CuentasUsuarios", b =>
                {
                    b.Property<int>("idCuentaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCuentaUsuario"));

                    b.Property<string>("contraseniaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaDesbloqueo")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoCuenta")
                        .HasColumnType("int");

                    b.Property<int>("idPersona")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ultimoInicioSesion")
                        .HasColumnType("datetime2");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idCuentaUsuario");

                    b.HasIndex("idEstadoCuenta");

                    b.HasIndex("idPersona")
                        .IsUnique();

                    b.HasIndex("idRol");

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("CuentasUsuarios");
                });

            modelBuilder.Entity("sigevet.Models.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("sigevet.Models.EspecialidadVeterinario", b =>
                {
                    b.Property<int>("idVeterinarioEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVeterinarioEspecialidad"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("idVeterinario")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idVeterinarioEspecialidad");

                    b.HasIndex("idEspecialidad");

                    b.HasIndex("idVeterinario", "idEspecialidad")
                        .IsUnique();

                    b.ToTable("EspecialidadesVeterinario");
                });

            modelBuilder.Entity("sigevet.Models.Especie", b =>
                {
                    b.Property<int>("idEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEspecie"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idEspecie");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("sigevet.Models.EsquemaVacunacion", b =>
                {
                    b.Property<int>("idEsquemaVacunacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEsquemaVacunacion"));

                    b.Property<int?>("edadMinimaDias")
                        .HasColumnType("int");

                    b.Property<string>("esquemaVacunacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idTipoVacuna")
                        .HasColumnType("int");

                    b.Property<int>("intervaloDias")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idEsquemaVacunacion");

                    b.HasIndex("idTipoVacuna");

                    b.ToTable("EsquemasVacunacion");
                });

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstado"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCategoriaEstado")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idEstado");

                    b.HasIndex("idCategoriaEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("sigevet.Models.InsumoSanitario", b =>
                {
                    b.Property<int>("idInsumoSanitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInsumoSanitario"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoInsumo")
                        .HasColumnType("int");

                    b.Property<int>("idTipoInsumo")
                        .HasColumnType("int");

                    b.Property<int>("idUnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("insumoSanitario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idInsumoSanitario");

                    b.HasIndex("idEstadoInsumo");

                    b.HasIndex("idTipoInsumo");

                    b.HasIndex("idUnidadMedida");

                    b.ToTable("InsumosSanitarios");
                });

            modelBuilder.Entity("sigevet.Models.Inventario", b =>
                {
                    b.Property<int>("idInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInventario"));

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idInsumoSanitario")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("stockMinimo")
                        .HasColumnType("int");

                    b.HasKey("idInventario");

                    b.HasIndex("idInsumoSanitario");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("sigevet.Models.Laboratorio", b =>
                {
                    b.Property<int>("idLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLaboratorio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("laboratorio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("idLaboratorio");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.Property<int>("idMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMascota"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoMascota")
                        .HasColumnType("int");

                    b.Property<int>("idRaza")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("seniasParticulares")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("idMascota");

                    b.HasIndex("idEstadoMascota");

                    b.HasIndex("idRaza");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("sigevet.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("idMovimientoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMovimientoInventario"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idBrigada")
                        .HasColumnType("int");

                    b.Property<int>("idInventario")
                        .HasColumnType("int");

                    b.Property<int>("idResponsable")
                        .HasColumnType("int");

                    b.Property<int>("idTipoMovimiento")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idMovimientoInventario");

                    b.HasIndex("idBrigada");

                    b.HasIndex("idInventario");

                    b.HasIndex("idResponsable");

                    b.HasIndex("idTipoMovimiento");

                    b.ToTable("MovimientoInventario");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.Property<int>("idPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersona"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoPersona")
                        .HasColumnType("int");

                    b.Property<int>("idTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("numeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("segundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idPersona");

                    b.HasIndex("idEstadoPersona");

                    b.HasIndex("idTipoIdentificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("sigevet.Models.Raza", b =>
                {
                    b.Property<int>("idRaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRaza"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEspecie")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRaza");

                    b.HasIndex("idEspecie");

                    b.ToTable("Razas");
                });

            modelBuilder.Entity("sigevet.Models.RefrescarToken", b =>
                {
                    b.Property<int>("idRefrescarToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRefrescarToken"));

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCuentaUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("userAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idRefrescarToken");

                    b.HasIndex("idCuentaUsuario");

                    b.ToTable("RefrescarTokens");
                });

            modelBuilder.Entity("sigevet.Models.RolParticipacion", b =>
                {
                    b.Property<int>("idRolParticipacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRolParticipacion"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("rolParticipacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRolParticipacion");

                    b.ToTable("RolesParticipacion");
                });

            modelBuilder.Entity("sigevet.Models.Roles", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRol"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("rolUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRol");

                    b.HasIndex("rolUsuario")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("sigevet.Models.TipoAlerta", b =>
                {
                    b.Property<int>("idTipoAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoAlerta"));

                    b.Property<string>("alerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idTipoAlerta");

                    b.ToTable("TiposAlerta");
                });

            modelBuilder.Entity("sigevet.Models.TipoContacto", b =>
                {
                    b.Property<int>("idTipoContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoContacto"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tipoContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoContacto");

                    b.ToTable("TiposContacto");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("idTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoIdentificacion"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoIdentificacion");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.TipoInsumo", b =>
                {
                    b.Property<int>("idTipoInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoInsumo"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tipoInsumo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoInsumo");

                    b.ToTable("TiposInsumo");
                });

            modelBuilder.Entity("sigevet.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("idTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoMovimiento"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoMovimiento");

                    b.ToTable("TiposMovimiento");
                });

            modelBuilder.Entity("sigevet.Models.TipoVacuna", b =>
                {
                    b.Property<int>("idTipoVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoVacuna"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tipoVacuna")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoVacuna");

                    b.ToTable("TiposVacuna");
                });

            modelBuilder.Entity("sigevet.Models.TokensCuentas", b =>
                {
                    b.Property<int>("idToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idToken"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaUso")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCuentaUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("usado")
                        .HasColumnType("bit");

                    b.HasKey("idToken");

                    b.HasIndex("idCuentaUsuario");

                    b.ToTable("TokensCuentas");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.Property<int>("idPersonaTut")
                        .HasColumnType("int");

                    b.Property<bool>("autorizaNotificaciones")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaActualizacionTutor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRegistroTutor")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoTutor")
                        .HasColumnType("int");

                    b.HasKey("idPersonaTut");

                    b.HasIndex("idEstadoTutor");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("sigevet.Models.TutorMascota", b =>
                {
                    b.Property<int>("idTutorMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTutorMascota"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int>("idPersonaTut")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("idTutorMascota");

                    b.HasIndex("idMascota");

                    b.HasIndex("idPersonaTut", "idMascota")
                        .IsUnique();

                    b.ToTable("TutoresMascota");
                });

            modelBuilder.Entity("sigevet.Models.UnidadMedida", b =>
                {
                    b.Property<int>("idUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUnidadMedida"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("unidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idUnidadMedida");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("sigevet.Models.Vacuna", b =>
                {
                    b.Property<int>("idVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVacuna"));

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaFabricacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoVacuna")
                        .HasColumnType("int");

                    b.Property<int>("idLaboratorio")
                        .HasColumnType("int");

                    b.Property<int>("idTipoVacuna")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("numeroLote")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("idVacuna");

                    b.HasIndex("idEstadoVacuna");

                    b.HasIndex("idLaboratorio");

                    b.HasIndex("idTipoVacuna");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("sigevet.Models.Vacunacion", b =>
                {
                    b.Property<int>("idVacunacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVacunacion"));

                    b.Property<decimal>("dosisAplicada")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEsquemaVacunacion")
                        .HasColumnType("int");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int>("idUnidadMedida")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("numeroDosis")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("proximaFecha")
                        .HasColumnType("date");

                    b.HasKey("idVacunacion");

                    b.HasIndex("idEsquemaVacunacion");

                    b.HasIndex("idMascota");

                    b.HasIndex("idUnidadMedida");

                    b.ToTable("Vacunaciones");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.Property<int>("idPersonaVet")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualizacionVeterinario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaRegistroVeterinario")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstadoDisponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("numeroTarjetaProfesional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idPersonaVet");

                    b.HasIndex("idEstadoDisponibilidad");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("sigevet.Models.AlertaVacunacion", b =>
                {
                    b.HasOne("sigevet.Models.TipoAlerta", "tipoAlerta")
                        .WithMany("alertasVacunacion")
                        .HasForeignKey("idTipoAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Vacunacion", "vacunaciones")
                        .WithMany("alertasVacunacion")
                        .HasForeignKey("idVacunacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tipoAlerta");

                    b.Navigation("vacunaciones");
                });

            modelBuilder.Entity("sigevet.Models.Brigada", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoBrigada")
                        .WithMany()
                        .HasForeignKey("idEstadoBrigada")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoBrigada");
                });

            modelBuilder.Entity("sigevet.Models.BrigadaVeterinario", b =>
                {
                    b.HasOne("sigevet.Models.Brigada", "brigadas")
                        .WithMany("veterinariosBrigada")
                        .HasForeignKey("idBrigada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.RolParticipacion", "rolParticipacion")
                        .WithMany("brigadasVeterinario")
                        .HasForeignKey("idRolParticipacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Veterinario", "veterinario")
                        .WithMany("brigadasVeterinario")
                        .HasForeignKey("idVeterinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("brigadas");

                    b.Navigation("rolParticipacion");

                    b.Navigation("veterinario");
                });

            modelBuilder.Entity("sigevet.Models.Contacto", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoContacto")
                        .WithMany()
                        .HasForeignKey("idEstadoContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Laboratorio", "laboratorio")
                        .WithMany("contactosLaboratorio")
                        .HasForeignKey("idLaboratorioContacto");

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithMany("contactosPersona")
                        .HasForeignKey("idPersonaContacto")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("sigevet.Models.TipoContacto", "tipoContacto")
                        .WithMany()
                        .HasForeignKey("idTipoContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoContacto");

                    b.Navigation("laboratorio");

                    b.Navigation("persona");

                    b.Navigation("tipoContacto");
                });

            modelBuilder.Entity("sigevet.Models.CuentasUsuarios", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoCuenta")
                        .WithMany()
                        .HasForeignKey("idEstadoCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithOne()
                        .HasForeignKey("sigevet.Models.CuentasUsuarios", "idPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Roles", "rolesUsuario")
                        .WithMany("cuentasUsuariosPorRol")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("estadoCuenta");

                    b.Navigation("persona");

                    b.Navigation("rolesUsuario");
                });

            modelBuilder.Entity("sigevet.Models.EspecialidadVeterinario", b =>
                {
                    b.HasOne("sigevet.Models.Especialidad", "especialidad")
                        .WithMany("veterinariosPorEspecialidad")
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Veterinario", "veterinarios")
                        .WithMany("especialidadesPorVeterinario")
                        .HasForeignKey("idVeterinario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");

                    b.Navigation("veterinarios");
                });

            modelBuilder.Entity("sigevet.Models.EsquemaVacunacion", b =>
                {
                    b.HasOne("sigevet.Models.TipoVacuna", "tipoVacuna")
                        .WithMany("esquemasVacunacion")
                        .HasForeignKey("idTipoVacuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoVacuna");
                });

            modelBuilder.Entity("sigevet.Models.Estado", b =>
                {
                    b.HasOne("sigevet.Models.CategoriaEstado", "categoriaEstado")
                        .WithMany("estadosPorCategoria")
                        .HasForeignKey("idCategoriaEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoriaEstado");
                });

            modelBuilder.Entity("sigevet.Models.InsumoSanitario", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoInsumo")
                        .WithMany()
                        .HasForeignKey("idEstadoInsumo")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoInsumo", "tipoInsumo")
                        .WithMany()
                        .HasForeignKey("idTipoInsumo")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.UnidadMedida", "unidadMedida")
                        .WithMany()
                        .HasForeignKey("idUnidadMedida")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoInsumo");

                    b.Navigation("tipoInsumo");

                    b.Navigation("unidadMedida");
                });

            modelBuilder.Entity("sigevet.Models.Inventario", b =>
                {
                    b.HasOne("sigevet.Models.InsumoSanitario", "insumoSanitario")
                        .WithMany("inventarios")
                        .HasForeignKey("idInsumoSanitario")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("insumoSanitario");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoMascota")
                        .WithMany()
                        .HasForeignKey("idEstadoMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Raza", "raza")
                        .WithMany()
                        .HasForeignKey("idRaza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("estadoMascota");

                    b.Navigation("raza");
                });

            modelBuilder.Entity("sigevet.Models.MovimientoInventario", b =>
                {
                    b.HasOne("sigevet.Models.Brigada", "brigada")
                        .WithMany("movimientosInventarios")
                        .HasForeignKey("idBrigada")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("sigevet.Models.Inventario", "inventario")
                        .WithMany("movimientosInventario")
                        .HasForeignKey("idInventario")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "responsableMovimiento")
                        .WithMany()
                        .HasForeignKey("idResponsable")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoMovimiento", "tipoMovimiento")
                        .WithMany()
                        .HasForeignKey("idTipoMovimiento")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("brigada");

                    b.Navigation("inventario");

                    b.Navigation("responsableMovimiento");

                    b.Navigation("tipoMovimiento");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoPersona")
                        .WithMany()
                        .HasForeignKey("idEstadoPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoIdentificacion", "tipoIdentificacion")
                        .WithMany("personas")
                        .HasForeignKey("idTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoPersona");

                    b.Navigation("tipoIdentificacion");
                });

            modelBuilder.Entity("sigevet.Models.Raza", b =>
                {
                    b.HasOne("sigevet.Models.Especie", "especie")
                        .WithMany("razasPorEspecie")
                        .HasForeignKey("idEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especie");
                });

            modelBuilder.Entity("sigevet.Models.RefrescarToken", b =>
                {
                    b.HasOne("sigevet.Models.CuentasUsuarios", "tokensPorCuentaUsuario")
                        .WithMany("refreshTokens")
                        .HasForeignKey("idCuentaUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tokensPorCuentaUsuario");
                });

            modelBuilder.Entity("sigevet.Models.TokensCuentas", b =>
                {
                    b.HasOne("sigevet.Models.CuentasUsuarios", "tokenCuentaUsuario")
                        .WithMany("tokensCuentas")
                        .HasForeignKey("idCuentaUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tokenCuentaUsuario");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoTutor")
                        .WithMany()
                        .HasForeignKey("idEstadoTutor")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithOne()
                        .HasForeignKey("sigevet.Models.Tutor", "idPersonaTut")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoTutor");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("sigevet.Models.TutorMascota", b =>
                {
                    b.HasOne("sigevet.Models.Mascota", "mascota")
                        .WithMany("tutoresMascota")
                        .HasForeignKey("idMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Tutor", "tutor")
                        .WithMany("mascotasPorTutor")
                        .HasForeignKey("idPersonaTut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("mascota");

                    b.Navigation("tutor");
                });

            modelBuilder.Entity("sigevet.Models.Vacuna", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoVacuna")
                        .WithMany()
                        .HasForeignKey("idEstadoVacuna")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Laboratorio", "laboratorio")
                        .WithMany()
                        .HasForeignKey("idLaboratorio")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("sigevet.Models.TipoVacuna", "tipoVacuna")
                        .WithMany()
                        .HasForeignKey("idTipoVacuna")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoVacuna");

                    b.Navigation("laboratorio");

                    b.Navigation("tipoVacuna");
                });

            modelBuilder.Entity("sigevet.Models.Vacunacion", b =>
                {
                    b.HasOne("sigevet.Models.EsquemaVacunacion", "esquemaVacunacion")
                        .WithMany("vacunaciones")
                        .HasForeignKey("idEsquemaVacunacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Mascota", "mascota")
                        .WithMany("vacunacionesMascota")
                        .HasForeignKey("idMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.UnidadMedida", "unidadMedida")
                        .WithMany()
                        .HasForeignKey("idUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("esquemaVacunacion");

                    b.Navigation("mascota");

                    b.Navigation("unidadMedida");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.HasOne("sigevet.Models.Estado", "estadoVeterinario")
                        .WithMany()
                        .HasForeignKey("idEstadoDisponibilidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sigevet.Models.Persona", "persona")
                        .WithOne()
                        .HasForeignKey("sigevet.Models.Veterinario", "idPersonaVet")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("estadoVeterinario");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("sigevet.Models.Brigada", b =>
                {
                    b.Navigation("movimientosInventarios");

                    b.Navigation("veterinariosBrigada");
                });

            modelBuilder.Entity("sigevet.Models.CategoriaEstado", b =>
                {
                    b.Navigation("estadosPorCategoria");
                });

            modelBuilder.Entity("sigevet.Models.CuentasUsuarios", b =>
                {
                    b.Navigation("refreshTokens");

                    b.Navigation("tokensCuentas");
                });

            modelBuilder.Entity("sigevet.Models.Especialidad", b =>
                {
                    b.Navigation("veterinariosPorEspecialidad");
                });

            modelBuilder.Entity("sigevet.Models.Especie", b =>
                {
                    b.Navigation("razasPorEspecie");
                });

            modelBuilder.Entity("sigevet.Models.EsquemaVacunacion", b =>
                {
                    b.Navigation("vacunaciones");
                });

            modelBuilder.Entity("sigevet.Models.InsumoSanitario", b =>
                {
                    b.Navigation("inventarios");
                });

            modelBuilder.Entity("sigevet.Models.Inventario", b =>
                {
                    b.Navigation("movimientosInventario");
                });

            modelBuilder.Entity("sigevet.Models.Laboratorio", b =>
                {
                    b.Navigation("contactosLaboratorio");
                });

            modelBuilder.Entity("sigevet.Models.Mascota", b =>
                {
                    b.Navigation("tutoresMascota");

                    b.Navigation("vacunacionesMascota");
                });

            modelBuilder.Entity("sigevet.Models.Persona", b =>
                {
                    b.Navigation("contactosPersona");
                });

            modelBuilder.Entity("sigevet.Models.RolParticipacion", b =>
                {
                    b.Navigation("brigadasVeterinario");
                });

            modelBuilder.Entity("sigevet.Models.Roles", b =>
                {
                    b.Navigation("cuentasUsuariosPorRol");
                });

            modelBuilder.Entity("sigevet.Models.TipoAlerta", b =>
                {
                    b.Navigation("alertasVacunacion");
                });

            modelBuilder.Entity("sigevet.Models.TipoIdentificacion", b =>
                {
                    b.Navigation("personas");
                });

            modelBuilder.Entity("sigevet.Models.TipoVacuna", b =>
                {
                    b.Navigation("esquemasVacunacion");
                });

            modelBuilder.Entity("sigevet.Models.Tutor", b =>
                {
                    b.Navigation("mascotasPorTutor");
                });

            modelBuilder.Entity("sigevet.Models.Vacunacion", b =>
                {
                    b.Navigation("alertasVacunacion");
                });

            modelBuilder.Entity("sigevet.Models.Veterinario", b =>
                {
                    b.Navigation("brigadasVeterinario");

                    b.Navigation("especialidadesPorVeterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
